"use client"

import { useEffect, useState } from "react"

export default function Home() {
  const [companyProfile, setCompanyProfile] = useState({
  name: "",
  address: "",
  phone: "",
  email: "",
})
useEffect(() => {
  const saved = localStorage.getItem("scopeguard_company")
  if (saved) {
    setCompanyProfile(JSON.parse(saved))
  }
}, [])

useEffect(() => {
  localStorage.setItem(
    "scopeguard_company",
    JSON.stringify(companyProfile)
  )
}, [companyProfile])
  const FREE_LIMIT = 3

  const [scopeChange, setScopeChange] = useState("")
  const [result, setResult] = useState("")
  const [count, setCount] = useState(0)
  const [paid, setPaid] = useState(false)
  const [status, setStatus] = useState("")
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    setCount(Number(localStorage.getItem("changeOrderCount") || "0"))

    if (localStorage.getItem("scopeguard_paid") === "true") {
      setPaid(true)
    }

    if (window.location.search.includes("paid=true")) {
      localStorage.setItem("scopeguard_paid", "true")
      setPaid(true)
      window.history.replaceState({}, "", "/")
    }
  }, [])

  async function generate() {
    if (!paid && count >= FREE_LIMIT) {
      setStatus("Free limit reached. Please upgrade to continue.")
      return
    }

    setLoading(true)
    setStatus("Generating professional change order…")
    setResult("")

    const res = await fetch("/api/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ scopeChange }),
    })

    if (!res.ok) {
      setStatus("Error generating change order.")
      setLoading(false)
      return
    }

    const data = await res.json()
    setResult(data.text)
    setStatus("")
    setLoading(false)

    if (!paid) {
      const newCount = count + 1
      localStorage.setItem("changeOrderCount", newCount.toString())
      setCount(newCount)
    }
  }

  async function upgrade() {
    setStatus("Redirecting to secure checkout…")

    const res = await fetch("/api/checkout", { method: "POST" })
    if (!res.ok) {
      setStatus("Checkout API error.")
      return
    }

    const data = await res.json()
    if (!data.url) {
      setStatus("No checkout URL returned.")
      return
    }

    window.location.href = data.url
  }

  function downloadPDF() {
  const content = document.getElementById("print-area")?.innerText
  if (!content) return

  const win = window.open("", "", "height=900,width=700")
  if (!win) return

  win.document.write(`
    <html>
      <head>
        <title>ScopeGuard Change Order</title>
        <style>
          body {
            font-family: system-ui, -apple-system, BlinkMacSystemFont;
            padding: 40px;
            color: #111;
          }

          .letterhead {
            display: flex;
            align-items: center;
            margin-bottom: 24px;
          }

          .logo {
            height: 60px;
            margin-right: 16px;
          }

          .company {
            line-height: 1.3;
          }

          h1 {
            margin: 0;
            font-size: 26px;
          }

          .subtitle {
            color: #555;
            font-size: 14px;
          }

          hr {
            margin: 24px 0;
            border: none;
            border-top: 1px solid #ddd;
          }

          pre {
            white-space: pre-wrap;
            font-size: 14px;
            line-height: 1.6;
          }

          .footer {
            margin-top: 48px;
            font-size: 12px;
            color: #777;
            text-align: center;
          }
        </style>
      </head>

      <body>
        <div class="letterhead">
          <img
            src="${window.location.origin}/logo.png"
            class="logo"
          />
          <div class="company">
            <h1>ScopeGuard</h1>
            <div class="subtitle">Professional Change Order</div>
          </div>
        </div>

        <div class="company-details">
          <strong>Your Company Name</strong><br/>
          123 Main Street, City, State<br/>
          (555) 123-4567 · info@yourcompany.com
        </div>

        <hr />

        <pre>${content}</pre>

        <div class="footer">
          Generated by ScopeGuard · ${new Date().toLocaleDateString()}
        </div>
      </body>
    </html>
  `)

  win.document.close()
  win.focus()
  win.print()
  win.close()
}

  const remaining = Math.max(0, FREE_LIMIT - count)
  const locked = !paid && count >= FREE_LIMIT

  return (
    <main
      style={{
        maxWidth: 640,
        margin: "60px auto",
        padding: 32,
        fontFamily: "system-ui",
        border: "1px solid #eee",
        borderRadius: 14,
        background: "#fff",
      }}
    >
      <h1 style={{ fontSize: 32, marginBottom: 8 }}>ScopeGuard</h1>
      <p style={{ fontSize: 18, color: "#555", marginBottom: 24 }}>
        Instantly generate professional construction change orders using AI.
      </p>

      {!paid && (
        <p style={{ marginBottom: 16 }}>
          Free uses remaining: <strong>{remaining}</strong>
        </p>
      )}
<h2 style={{ marginTop: 32, marginBottom: 12 }}>Company Profile</h2>

<input
  placeholder="Company Name"
  value={companyProfile.name}
  onChange={(e) =>
    setCompanyProfile({ ...companyProfile, name: e.target.value })
  }
  style={{
    width: "100%",
    padding: 10,
    marginBottom: 8,
    borderRadius: 6,
    border: "1px solid #ccc",
  }}
/>

<input
  placeholder="Company Address"
  value={companyProfile.address}
  onChange={(e) =>
    setCompanyProfile({ ...companyProfile, address: e.target.value })
  }
  style={{
    width: "100%",
    padding: 10,
    marginBottom: 8,
    borderRadius: 6,
    border: "1px solid #ccc",
  }}
/>

<input
  placeholder="Phone Number"
  value={companyProfile.phone}
  onChange={(e) =>
    setCompanyProfile({ ...companyProfile, phone: e.target.value })
  }
  style={{
    width: "100%",
    padding: 10,
    marginBottom: 8,
    borderRadius: 6,
    border: "1px solid #ccc",
  }}
/>

<input
  placeholder="Email Address"
  value={companyProfile.email}
  onChange={(e) =>
    setCompanyProfile({ ...companyProfile, email: e.target.value })
  }
  style={{
    width: "100%",
    padding: 10,
    marginBottom: 24,
    borderRadius: 6,
    border: "1px solid #ccc",
  }}
/>
      <textarea
        placeholder="Example: Client requested adding recessed lighting and upgrading countertops to quartz."
        value={scopeChange}
        onChange={(e) => setScopeChange(e.target.value)}
        style={{
          width: "100%",
          height: 140,
          padding: 12,
          fontSize: 15,
          border: "1px solid #ccc",
          borderRadius: 8,
          marginBottom: 16,
        }}
      />

      <button
        onClick={generate}
        disabled={locked || loading || !scopeChange.trim()}
        style={{
          width: "100%",
          padding: "12px 16px",
          fontSize: 16,
          background: locked ? "#ccc" : "#000",
          color: "#fff",
          border: "none",
          borderRadius: 8,
          cursor: locked ? "not-allowed" : "pointer",
        }}
      >
        {loading ? "Generating…" : "Generate Professional Change Order"}
      </button>

      {locked && (
        <div style={{ marginTop: 20 }}>
          <p style={{ color: "red" }}>You’ve reached your free limit.</p>
          <button
            onClick={upgrade}
            style={{
              width: "100%",
              padding: "14px",
              background: "#000",
              color: "#fff",
              border: "none",
              borderRadius: 8,
              cursor: "pointer",
            }}
          >
            Unlock Unlimited Change Orders
          </button>
        </div>
      )}

      {status && <p style={{ marginTop: 16 }}>{status}</p>}

      {result && (
        <div style={{ marginTop: 28 }}>
          <h3>Generated Change Order</h3>

          <div
            id="print-area"
            style={{
              background: "#f5f5f5",
              padding: 16,
              borderRadius: 8,
              whiteSpace: "pre-wrap",
            }}
          >
            {result}
          </div>

          <button
            onClick={downloadPDF}
            style={{
              marginTop: 12,
              padding: "10px 14px",
              background: "#fff",
              border: "1px solid #000",
              borderRadius: 6,
              cursor: "pointer",
            }}
          >
            Download PDF
          </button>
        </div>
      )}

      <p
        style={{
          marginTop: 40,
          fontSize: 12,
          color: "#888",
          textAlign: "center",
        }}
      >
        Secure payments powered by Stripe.
      </p>
    </main>
  )
}